[dependencies]
rustpress-sdk = "*"

[package]
description = ""
icon = "assets/icon.png"
id = "com.example.poetry"
name = "poetry"
title = "poetry"
version = "0.1.0"

[plugin]
binary = "plugin.wasm"
hooks = ["on_post_published"]
