[workspace]

[package]
name = "poetry-plugin"
version = "1.0.0"
edition = "2024"

[lib]
name = "poetry_plugin"
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.36.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"